#!/usr/bin/env bash
# Generate the synthetic corpus using Nix-installable tools.
#
# Each tool produces files of its native format. We capture a few "the same
# logical content, generated by different tools" sets so the audit can
# detect encoder divergence (the whole point of the synthetic corpus).
#
# Tools we rely on (provide via nix devshell):
#   - ImageMagick (`convert`) — produces PNG, JPEG, BMP, TGA, TIFF, GIF
#   - libreoffice (`soffice --headless --convert-to`) — produces docx, xlsx, pptx, odt, pdf
#   - ghostscript (`gs`) — produces PDF
#   - pdflatex — produces PDF
#   - pandoc — produces docx, epub, pdf
#   - ffmpeg — produces wav, aiff, flac
#   - pngquant / oxipng / optipng — produces re-encoded PNG (different encoder fingerprints)
#   - gzip, pigz — produces .gz
#   - tar, bsdtar — produces .tar (for completeness, even though tar is out of scope for fingerprinting)
#   - zip (Info-ZIP) — produces .zip (DEFLATE)
#
# When a tool isn't available, skip it gracefully and log to skipped.log.
#
# Output structure mirrors corpus_*/<format>/<generator>/<file>
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AUDIT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
# Synthetic-generated files land in the public corpus alongside any
# publicly-sourced files. Source/origin is encoded in the per-generator subdir.
CORPUS="$AUDIT_DIR/corpus_public"
SKIPPED="$AUDIT_DIR/results/synthetic-skipped.log"
mkdir -p "$AUDIT_DIR/results"
: > "$SKIPPED"

have() { command -v "$1" >/dev/null 2>&1; }
skip() { echo "$@" >> "$SKIPPED"; echo "SKIP: $*" >&2; }

# A reusable "logical source" — same content, different generators
TMP_SRC="$(mktemp -d)"
trap 'rm -rf "$TMP_SRC"' EXIT

# 1. Generate a base PNG via ImageMagick to use as input for cross-encoder PNGs
if have convert; then
    convert -size 256x256 gradient:red-blue "$TMP_SRC/base.png" 2>/dev/null
    convert -size 1024x768 plasma: "$TMP_SRC/big.png" 2>/dev/null
fi

# 2. Generate a base text doc to use as input for various office formats
cat > "$TMP_SRC/base.txt" <<EOF
The quick brown fox jumps over the lazy dog.
0123456789 !@#\$%^&*()_+
Unicode: αβγδε 漢字 🦊
EOF

# 3. Generate a base PCM WAV
if have ffmpeg; then
    ffmpeg -hide_banner -loglevel error \
        -f lavfi -i "sine=frequency=440:duration=2" \
        -ac 2 -ar 44100 -y "$TMP_SRC/base.wav" 2>/dev/null
fi

# ────────────────────────────────────────────────────────────────
# PNG generators
# ────────────────────────────────────────────────────────────────
if have convert && [[ -f "$TMP_SRC/base.png" ]]; then
    mkdir -p "$CORPUS/png/imagemagick"
    cp "$TMP_SRC/base.png" "$CORPUS/png/imagemagick/gradient.png"
    convert -size 64x64 xc:white "$CORPUS/png/imagemagick/white.png" 2>/dev/null
    convert "$TMP_SRC/big.png" "$CORPUS/png/imagemagick/plasma.png" 2>/dev/null
fi
for tool in pngquant oxipng optipng; do
    if have "$tool" && [[ -f "$TMP_SRC/base.png" ]]; then
        mkdir -p "$CORPUS/png/$tool"
        cp "$TMP_SRC/base.png" "$TMP_SRC/work.png"
        case "$tool" in
            pngquant) pngquant --force --output "$CORPUS/png/$tool/gradient.png" "$TMP_SRC/work.png" 2>/dev/null ;;
            oxipng)   cp "$TMP_SRC/work.png" "$CORPUS/png/$tool/gradient.png" && oxipng "$CORPUS/png/$tool/gradient.png" 2>/dev/null ;;
            optipng)  cp "$TMP_SRC/work.png" "$CORPUS/png/$tool/gradient.png" && optipng -quiet "$CORPUS/png/$tool/gradient.png" 2>/dev/null ;;
        esac
    fi
done

# ────────────────────────────────────────────────────────────────
# JPEG generators
# ────────────────────────────────────────────────────────────────
if have convert && [[ -f "$TMP_SRC/base.png" ]]; then
    mkdir -p "$CORPUS/jpeg/imagemagick"
    convert "$TMP_SRC/base.png" "$CORPUS/jpeg/imagemagick/gradient.jpg" 2>/dev/null
    convert "$TMP_SRC/base.png" -quality 75 "$CORPUS/jpeg/imagemagick/gradient_q75.jpg" 2>/dev/null
    convert "$TMP_SRC/base.png" -quality 95 "$CORPUS/jpeg/imagemagick/gradient_q95.jpg" 2>/dev/null
fi
if have cjpeg && [[ -f "$TMP_SRC/base.png" ]]; then
    mkdir -p "$CORPUS/jpeg/libjpeg-turbo"
    convert "$TMP_SRC/base.png" "$TMP_SRC/base.ppm" 2>/dev/null
    cjpeg -quality 75 -outfile "$CORPUS/jpeg/libjpeg-turbo/gradient.jpg" "$TMP_SRC/base.ppm" 2>/dev/null
fi

# ────────────────────────────────────────────────────────────────
# BMP / TGA / TIFF
# ────────────────────────────────────────────────────────────────
if have convert && [[ -f "$TMP_SRC/base.png" ]]; then
    for fmt in bmp tga tiff; do
        mkdir -p "$CORPUS/$fmt/imagemagick"
        convert "$TMP_SRC/base.png" "$CORPUS/$fmt/imagemagick/gradient.$fmt" 2>/dev/null
    done
    # TIFF with LZW compression
    convert "$TMP_SRC/base.png" -compress lzw "$CORPUS/tiff/imagemagick/gradient_lzw.tiff" 2>/dev/null
    # TIFF with packbits
    convert "$TMP_SRC/base.png" -compress rle "$CORPUS/tiff/imagemagick/gradient_packbits.tiff" 2>/dev/null
fi

# ────────────────────────────────────────────────────────────────
# GIF
# ────────────────────────────────────────────────────────────────
if have convert && [[ -f "$TMP_SRC/base.png" ]]; then
    mkdir -p "$CORPUS/gif/imagemagick"
    convert "$TMP_SRC/base.png" "$CORPUS/gif/imagemagick/gradient.gif" 2>/dev/null
fi
if have gifsicle && [[ -f "$CORPUS/gif/imagemagick/gradient.gif" ]]; then
    mkdir -p "$CORPUS/gif/gifsicle"
    gifsicle "$CORPUS/gif/imagemagick/gradient.gif" -o "$CORPUS/gif/gifsicle/gradient.gif" 2>/dev/null
fi

# ────────────────────────────────────────────────────────────────
# PDF generators
# ────────────────────────────────────────────────────────────────
if have soffice; then
    mkdir -p "$CORPUS/pdf/libreoffice"
    soffice --headless --convert-to pdf --outdir "$CORPUS/pdf/libreoffice" "$TMP_SRC/base.txt" 2>/dev/null
fi
if have pandoc; then
    mkdir -p "$CORPUS/pdf/pandoc"
    pandoc "$TMP_SRC/base.txt" -o "$CORPUS/pdf/pandoc/base.pdf" 2>/dev/null
fi
if have gs && have convert && [[ -f "$TMP_SRC/base.png" ]]; then
    mkdir -p "$CORPUS/pdf/ghostscript"
    convert "$TMP_SRC/base.png" "$CORPUS/pdf/ghostscript/image.pdf" 2>/dev/null
fi
if have pdflatex; then
    mkdir -p "$CORPUS/pdf/pdflatex"
    pushd "$TMP_SRC" >/dev/null
    cat > tex_doc.tex <<'EOF'
\documentclass{article}
\begin{document}
The quick brown fox jumps over the lazy dog.
\end{document}
EOF
    pdflatex -interaction=batchmode tex_doc.tex >/dev/null 2>&1
    [[ -f tex_doc.pdf ]] && cp tex_doc.pdf "$CORPUS/pdf/pdflatex/sample.pdf"
    popd >/dev/null
fi

# ────────────────────────────────────────────────────────────────
# Office formats
# ────────────────────────────────────────────────────────────────
if have soffice; then
    for fmt in docx xlsx pptx odt; do
        mkdir -p "$CORPUS/$fmt/libreoffice"
    done
    soffice --headless --convert-to docx --outdir "$CORPUS/docx/libreoffice" "$TMP_SRC/base.txt" 2>/dev/null
    soffice --headless --convert-to odt --outdir "$CORPUS/odt/libreoffice" "$TMP_SRC/base.txt" 2>/dev/null
fi

# ────────────────────────────────────────────────────────────────
# EPUB
# ────────────────────────────────────────────────────────────────
if have pandoc; then
    mkdir -p "$CORPUS/epub/pandoc"
    pandoc "$TMP_SRC/base.txt" -o "$CORPUS/epub/pandoc/base.epub" 2>/dev/null
fi

# ────────────────────────────────────────────────────────────────
# Audio: WAV / AIFF / FLAC
# ────────────────────────────────────────────────────────────────
if have ffmpeg && [[ -f "$TMP_SRC/base.wav" ]]; then
    mkdir -p "$CORPUS/wav/ffmpeg" "$CORPUS/aiff/ffmpeg" "$CORPUS/flac/ffmpeg"
    cp "$TMP_SRC/base.wav" "$CORPUS/wav/ffmpeg/sine.wav"
    ffmpeg -hide_banner -loglevel error -y -i "$TMP_SRC/base.wav" -f aiff "$CORPUS/aiff/ffmpeg/sine.aiff" 2>/dev/null
    ffmpeg -hide_banner -loglevel error -y -i "$TMP_SRC/base.wav" -c:a flac "$CORPUS/flac/ffmpeg/sine.flac" 2>/dev/null
fi
if have flac && [[ -f "$TMP_SRC/base.wav" ]]; then
    mkdir -p "$CORPUS/flac/libflac"
    flac --silent -f -o "$CORPUS/flac/libflac/sine.flac" "$TMP_SRC/base.wav" 2>/dev/null
fi
if have sox && [[ -f "$TMP_SRC/base.wav" ]]; then
    mkdir -p "$CORPUS/wav/sox" "$CORPUS/aiff/sox"
    sox "$TMP_SRC/base.wav" "$CORPUS/wav/sox/sine.wav" 2>/dev/null
    sox "$TMP_SRC/base.wav" "$CORPUS/aiff/sox/sine.aiff" 2>/dev/null
fi

# ────────────────────────────────────────────────────────────────
# Compressed containers: gzip, zip
# ────────────────────────────────────────────────────────────────
if have gzip; then
    mkdir -p "$CORPUS/gzip/gnu_gzip"
    gzip -c -9 "$TMP_SRC/base.txt" > "$CORPUS/gzip/gnu_gzip/base.txt.gz"
    gzip -c -1 "$TMP_SRC/base.txt" > "$CORPUS/gzip/gnu_gzip/base.txt.fast.gz"
fi
if have pigz; then
    mkdir -p "$CORPUS/gzip/pigz"
    pigz -c -9 "$TMP_SRC/base.txt" > "$CORPUS/gzip/pigz/base.txt.gz"
fi
if have zip; then
    mkdir -p "$CORPUS/zip/info-zip"
    (cd "$TMP_SRC" && zip -q -9 "$CORPUS/zip/info-zip/base.zip" base.txt)
fi
if have 7z; then
    mkdir -p "$CORPUS/zip/p7zip"
    7z a -tzip "$CORPUS/zip/p7zip/base.zip" "$TMP_SRC/base.txt" >/dev/null 2>&1
fi

echo "Synthetic corpus generation complete."
echo "Files generated:"
find "$CORPUS" -type f | wc -l
echo "Skipped tools (not installed):"
cat "$SKIPPED" 2>/dev/null | wc -l
echo "(see $SKIPPED for details)"
